cmake_minimum_required(VERSION 3.8)
project(moz1_moveit_config)

find_package(ament_cmake REQUIRED)

install(
  DIRECTORY config launch rviz
  DESTINATION share/${PROJECT_NAME}
)

# Hidden file telling MoveItConfigsBuilder the URDF/SRDF locations.
install(
  FILES .setup_assistant
  DESTINATION share/${PROJECT_NAME}
)

ament_package()
